<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mytyposcripttsconfig"
 *
 * Auto generated by Extension Builder 2018-12-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 8 Template for learning Typoscript',
    'description' => 'Template Extension for learning Typoscript',
    'category' => 'templates',
    'author' => 'Wolfgang Wagner',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
